#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanGao
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Thaytri")]
	public partial class QLBanGaoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBangSanPham(BangSanPham instance);
    partial void UpdateBangSanPham(BangSanPham instance);
    partial void DeleteBangSanPham(BangSanPham instance);
    partial void InsertChiTietKhuyenMai(ChiTietKhuyenMai instance);
    partial void UpdateChiTietKhuyenMai(ChiTietKhuyenMai instance);
    partial void DeleteChiTietKhuyenMai(ChiTietKhuyenMai instance);
    partial void InsertChiTietSp(ChiTietSp instance);
    partial void UpdateChiTietSp(ChiTietSp instance);
    partial void DeleteChiTietSp(ChiTietSp instance);
    partial void InsertDanhmucTinTuc(DanhmucTinTuc instance);
    partial void UpdateDanhmucTinTuc(DanhmucTinTuc instance);
    partial void DeleteDanhmucTinTuc(DanhmucTinTuc instance);
    partial void InsertGioHang(GioHang instance);
    partial void UpdateGioHang(GioHang instance);
    partial void DeleteGioHang(GioHang instance);
    partial void InsertKhuyen_mai(Khuyen_mai instance);
    partial void UpdateKhuyen_mai(Khuyen_mai instance);
    partial void DeleteKhuyen_mai(Khuyen_mai instance);
    partial void Insertlien_He(lien_He instance);
    partial void Updatelien_He(lien_He instance);
    partial void Deletelien_He(lien_He instance);
    partial void InsertThongTinDatHang(ThongTinDatHang instance);
    partial void UpdateThongTinDatHang(ThongTinDatHang instance);
    partial void DeleteThongTinDatHang(ThongTinDatHang instance);
    partial void InsertThongTinKhachHang(ThongTinKhachHang instance);
    partial void UpdateThongTinKhachHang(ThongTinKhachHang instance);
    partial void DeleteThongTinKhachHang(ThongTinKhachHang instance);
    partial void InsertTinTuc(TinTuc instance);
    partial void UpdateTinTuc(TinTuc instance);
    partial void DeleteTinTuc(TinTuc instance);
    partial void InsertDanhMucKhuyenmai(DanhMucKhuyenmai instance);
    partial void UpdateDanhMucKhuyenmai(DanhMucKhuyenmai instance);
    partial void DeleteDanhMucKhuyenmai(DanhMucKhuyenmai instance);
    partial void InsertDanhmucSp(DanhmucSp instance);
    partial void UpdateDanhmucSp(DanhmucSp instance);
    partial void DeleteDanhmucSp(DanhmucSp instance);
    #endregion
		
		public QLBanGaoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ThaytriConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanGaoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanGaoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanGaoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBanGaoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BangSanPham> BangSanPhams
		{
			get
			{
				return this.GetTable<BangSanPham>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietKhuyenMai> ChiTietKhuyenMais
		{
			get
			{
				return this.GetTable<ChiTietKhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietSp> ChiTietSps
		{
			get
			{
				return this.GetTable<ChiTietSp>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietTinTuc> ChiTietTinTucs
		{
			get
			{
				return this.GetTable<ChiTietTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<DanhmucTinTuc> DanhmucTinTucs
		{
			get
			{
				return this.GetTable<DanhmucTinTuc>();
			}
		}
		
		public System.Data.Linq.Table<GioHang> GioHangs
		{
			get
			{
				return this.GetTable<GioHang>();
			}
		}
		
		public System.Data.Linq.Table<Khuyen_mai> Khuyen_mais
		{
			get
			{
				return this.GetTable<Khuyen_mai>();
			}
		}
		
		public System.Data.Linq.Table<lien_He> lien_Hes
		{
			get
			{
				return this.GetTable<lien_He>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinDatHang> ThongTinDatHangs
		{
			get
			{
				return this.GetTable<ThongTinDatHang>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinKhachHang> ThongTinKhachHangs
		{
			get
			{
				return this.GetTable<ThongTinKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<TinTuc> TinTucs
		{
			get
			{
				return this.GetTable<TinTuc>();
			}
		}
		
		public System.Data.Linq.Table<DanhMucKhuyenmai> DanhMucKhuyenmais
		{
			get
			{
				return this.GetTable<DanhMucKhuyenmai>();
			}
		}
		
		public System.Data.Linq.Table<DanhmucSp> DanhmucSps
		{
			get
			{
				return this.GetTable<DanhmucSp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangSanPham")]
	public partial class BangSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSanPham;
		
		private string _HinhAnh;
		
		private string _TenSanPham;
		
		private string _Gia;
		
		private string _IdDanhMucSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSanPhamChanging(int value);
    partial void OnIdSanPhamChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    partial void OnIdDanhMucSanPhamChanging(string value);
    partial void OnIdDanhMucSanPhamChanged();
    #endregion
		
		public BangSanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSanPham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSanPham
		{
			get
			{
				return this._IdSanPham;
			}
			set
			{
				if ((this._IdSanPham != value))
				{
					this.OnIdSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdSanPham = value;
					this.SendPropertyChanged("IdSanPham");
					this.OnIdSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(50)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NVarChar(50)")]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucSanPham", DbType="NVarChar(50)")]
		public string IdDanhMucSanPham
		{
			get
			{
				return this._IdDanhMucSanPham;
			}
			set
			{
				if ((this._IdDanhMucSanPham != value))
				{
					this.OnIdDanhMucSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucSanPham = value;
					this.SendPropertyChanged("IdDanhMucSanPham");
					this.OnIdDanhMucSanPhamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietKhuyenMai")]
	public partial class ChiTietKhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HinhanhKhuyenMai;
		
		private int _IdKhuyenMai;
		
		private string _Ten;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _NoiDung;
		
		private string _IdDanhMucKhuyenMai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHinhanhKhuyenMaiChanging(string value);
    partial void OnHinhanhKhuyenMaiChanged();
    partial void OnIdKhuyenMaiChanging(int value);
    partial void OnIdKhuyenMaiChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnIdDanhMucKhuyenMaiChanging(string value);
    partial void OnIdDanhMucKhuyenMaiChanged();
    #endregion
		
		public ChiTietKhuyenMai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhanhKhuyenMai", DbType="NVarChar(MAX)")]
		public string HinhanhKhuyenMai
		{
			get
			{
				return this._HinhanhKhuyenMai;
			}
			set
			{
				if ((this._HinhanhKhuyenMai != value))
				{
					this.OnHinhanhKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._HinhanhKhuyenMai = value;
					this.SendPropertyChanged("HinhanhKhuyenMai");
					this.OnHinhanhKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhuyenMai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKhuyenMai
		{
			get
			{
				return this._IdKhuyenMai;
			}
			set
			{
				if ((this._IdKhuyenMai != value))
				{
					this.OnIdKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._IdKhuyenMai = value;
					this.SendPropertyChanged("IdKhuyenMai");
					this.OnIdKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(MAX)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucKhuyenMai", DbType="NChar(10)")]
		public string IdDanhMucKhuyenMai
		{
			get
			{
				return this._IdDanhMucKhuyenMai;
			}
			set
			{
				if ((this._IdDanhMucKhuyenMai != value))
				{
					this.OnIdDanhMucKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucKhuyenMai = value;
					this.SendPropertyChanged("IdDanhMucKhuyenMai");
					this.OnIdDanhMucKhuyenMaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietSp")]
	public partial class ChiTietSp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSanPham;
		
		private string _TenSanPham;
		
		private string _MoTa;
		
		private string _HinhAnh;
		
		private string _Gia;
		
		private string _IdDanhMucSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSanPhamChanging(int value);
    partial void OnIdSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    partial void OnIdDanhMucSanPhamChanging(string value);
    partial void OnIdDanhMucSanPhamChanged();
    #endregion
		
		public ChiTietSp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSanPham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSanPham
		{
			get
			{
				return this._IdSanPham;
			}
			set
			{
				if ((this._IdSanPham != value))
				{
					this.OnIdSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdSanPham = value;
					this.SendPropertyChanged("IdSanPham");
					this.OnIdSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(MAX)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NVarChar(50)")]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucSanPham", DbType="NVarChar(MAX)")]
		public string IdDanhMucSanPham
		{
			get
			{
				return this._IdDanhMucSanPham;
			}
			set
			{
				if ((this._IdDanhMucSanPham != value))
				{
					this.OnIdDanhMucSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucSanPham = value;
					this.SendPropertyChanged("IdDanhMucSanPham");
					this.OnIdDanhMucSanPhamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietTinTuc")]
	public partial class ChiTietTinTuc
	{
		
		private string _IdTinTuc;
		
		private string _Ten;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _Noidung;
		
		private string _HinhAnh;
		
		private string _IdDanhMucTT;
		
		public ChiTietTinTuc()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTinTuc", DbType="NVarChar(50)")]
		public string IdTinTuc
		{
			get
			{
				return this._IdTinTuc;
			}
			set
			{
				if ((this._IdTinTuc != value))
				{
					this._IdTinTuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this._Ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung", DbType="NVarChar(50)")]
		public string Noidung
		{
			get
			{
				return this._Noidung;
			}
			set
			{
				if ((this._Noidung != value))
				{
					this._Noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this._HinhAnh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucTT", DbType="NVarChar(50)")]
		public string IdDanhMucTT
		{
			get
			{
				return this._IdDanhMucTT;
			}
			set
			{
				if ((this._IdDanhMucTT != value))
				{
					this._IdDanhMucTT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhmucTinTuc")]
	public partial class DanhmucTinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDanhMucTT;
		
		private string _TenDanhMucTT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDanhMucTTChanging(int value);
    partial void OnIdDanhMucTTChanged();
    partial void OnTenDanhMucTTChanging(string value);
    partial void OnTenDanhMucTTChanged();
    #endregion
		
		public DanhmucTinTuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucTT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDanhMucTT
		{
			get
			{
				return this._IdDanhMucTT;
			}
			set
			{
				if ((this._IdDanhMucTT != value))
				{
					this.OnIdDanhMucTTChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucTT = value;
					this.SendPropertyChanged("IdDanhMucTT");
					this.OnIdDanhMucTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMucTT", DbType="NVarChar(50)")]
		public string TenDanhMucTT
		{
			get
			{
				return this._TenDanhMucTT;
			}
			set
			{
				if ((this._TenDanhMucTT != value))
				{
					this.OnTenDanhMucTTChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMucTT = value;
					this.SendPropertyChanged("TenDanhMucTT");
					this.OnTenDanhMucTTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioHang")]
	public partial class GioHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDonHang;
		
		private string _IdSanPham;
		
		private string _TenSanPham;
		
		private System.Nullable<int> _Soluong;
		
		private string _Gia;
		
		private System.Nullable<double> _TongTien;
		
		private System.Nullable<int> _TongDonHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDonHangChanging(int value);
    partial void OnIdDonHangChanged();
    partial void OnIdSanPhamChanging(string value);
    partial void OnIdSanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnSoluongChanging(System.Nullable<int> value);
    partial void OnSoluongChanged();
    partial void OnGiaChanging(string value);
    partial void OnGiaChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    partial void OnTongDonHangChanging(System.Nullable<int> value);
    partial void OnTongDonHangChanged();
    #endregion
		
		public GioHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDonHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDonHang
		{
			get
			{
				return this._IdDonHang;
			}
			set
			{
				if ((this._IdDonHang != value))
				{
					this.OnIdDonHangChanging(value);
					this.SendPropertyChanging();
					this._IdDonHang = value;
					this.SendPropertyChanged("IdDonHang");
					this.OnIdDonHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSanPham", DbType="NVarChar(50)")]
		public string IdSanPham
		{
			get
			{
				return this._IdSanPham;
			}
			set
			{
				if ((this._IdSanPham != value))
				{
					this.OnIdSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdSanPham = value;
					this.SendPropertyChanged("IdSanPham");
					this.OnIdSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(50)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong", DbType="Int")]
		public System.Nullable<int> Soluong
		{
			get
			{
				return this._Soluong;
			}
			set
			{
				if ((this._Soluong != value))
				{
					this.OnSoluongChanging(value);
					this.SendPropertyChanging();
					this._Soluong = value;
					this.SendPropertyChanged("Soluong");
					this.OnSoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="NVarChar(50)")]
		public string Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDonHang", DbType="Int")]
		public System.Nullable<int> TongDonHang
		{
			get
			{
				return this._TongDonHang;
			}
			set
			{
				if ((this._TongDonHang != value))
				{
					this.OnTongDonHangChanging(value);
					this.SendPropertyChanging();
					this._TongDonHang = value;
					this.SendPropertyChanged("TongDonHang");
					this.OnTongDonHangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khuyen_mai")]
	public partial class Khuyen_mai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKhuyenMai;
		
		private string _HinhAnh;
		
		private string _TenSanPham;
		
		private string _IdDanhMucKhuyenMai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKhuyenMaiChanging(int value);
    partial void OnIdKhuyenMaiChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnIdDanhMucKhuyenMaiChanging(string value);
    partial void OnIdDanhMucKhuyenMaiChanged();
    #endregion
		
		public Khuyen_mai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhuyenMai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKhuyenMai
		{
			get
			{
				return this._IdKhuyenMai;
			}
			set
			{
				if ((this._IdKhuyenMai != value))
				{
					this.OnIdKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._IdKhuyenMai = value;
					this.SendPropertyChanged("IdKhuyenMai");
					this.OnIdKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(50)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucKhuyenMai", DbType="NVarChar(50)")]
		public string IdDanhMucKhuyenMai
		{
			get
			{
				return this._IdDanhMucKhuyenMai;
			}
			set
			{
				if ((this._IdDanhMucKhuyenMai != value))
				{
					this.OnIdDanhMucKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucKhuyenMai = value;
					this.SendPropertyChanged("IdDanhMucKhuyenMai");
					this.OnIdDanhMucKhuyenMaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lien_He")]
	public partial class lien_He : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdLienHe;
		
		private string _HinhAnh;
		
		private string _WebsiteGaoSach;
		
		private string _DiaChiGaoSach;
		
		private System.Nullable<int> _SDTGaoSach;
		
		private string _EmailGaoSach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdLienHeChanging(int value);
    partial void OnIdLienHeChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnWebsiteGaoSachChanging(string value);
    partial void OnWebsiteGaoSachChanged();
    partial void OnDiaChiGaoSachChanging(string value);
    partial void OnDiaChiGaoSachChanged();
    partial void OnSDTGaoSachChanging(System.Nullable<int> value);
    partial void OnSDTGaoSachChanged();
    partial void OnEmailGaoSachChanging(string value);
    partial void OnEmailGaoSachChanged();
    #endregion
		
		public lien_He()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdLienHe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdLienHe
		{
			get
			{
				return this._IdLienHe;
			}
			set
			{
				if ((this._IdLienHe != value))
				{
					this.OnIdLienHeChanging(value);
					this.SendPropertyChanging();
					this._IdLienHe = value;
					this.SendPropertyChanged("IdLienHe");
					this.OnIdLienHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebsiteGaoSach", DbType="NVarChar(50)")]
		public string WebsiteGaoSach
		{
			get
			{
				return this._WebsiteGaoSach;
			}
			set
			{
				if ((this._WebsiteGaoSach != value))
				{
					this.OnWebsiteGaoSachChanging(value);
					this.SendPropertyChanging();
					this._WebsiteGaoSach = value;
					this.SendPropertyChanged("WebsiteGaoSach");
					this.OnWebsiteGaoSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiGaoSach", DbType="NVarChar(50)")]
		public string DiaChiGaoSach
		{
			get
			{
				return this._DiaChiGaoSach;
			}
			set
			{
				if ((this._DiaChiGaoSach != value))
				{
					this.OnDiaChiGaoSachChanging(value);
					this.SendPropertyChanging();
					this._DiaChiGaoSach = value;
					this.SendPropertyChanged("DiaChiGaoSach");
					this.OnDiaChiGaoSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTGaoSach", DbType="Int")]
		public System.Nullable<int> SDTGaoSach
		{
			get
			{
				return this._SDTGaoSach;
			}
			set
			{
				if ((this._SDTGaoSach != value))
				{
					this.OnSDTGaoSachChanging(value);
					this.SendPropertyChanging();
					this._SDTGaoSach = value;
					this.SendPropertyChanged("SDTGaoSach");
					this.OnSDTGaoSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailGaoSach", DbType="NVarChar(50)")]
		public string EmailGaoSach
		{
			get
			{
				return this._EmailGaoSach;
			}
			set
			{
				if ((this._EmailGaoSach != value))
				{
					this.OnEmailGaoSachChanging(value);
					this.SendPropertyChanging();
					this._EmailGaoSach = value;
					this.SendPropertyChanged("EmailGaoSach");
					this.OnEmailGaoSachChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinDatHang")]
	public partial class ThongTinDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKhachHang;
		
		private string _TenKhachHang;
		
		private System.Nullable<int> _SDTKhachHang;
		
		private string _Email;
		
		private string _DiaChiGiaoHang;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKhachHangChanging(int value);
    partial void OnIdKhachHangChanged();
    partial void OnTenKhachHangChanging(string value);
    partial void OnTenKhachHangChanged();
    partial void OnSDTKhachHangChanging(System.Nullable<int> value);
    partial void OnSDTKhachHangChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiGiaoHangChanging(string value);
    partial void OnDiaChiGiaoHangChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public ThongTinDatHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKhachHang
		{
			get
			{
				return this._IdKhachHang;
			}
			set
			{
				if ((this._IdKhachHang != value))
				{
					this.OnIdKhachHangChanging(value);
					this.SendPropertyChanging();
					this._IdKhachHang = value;
					this.SendPropertyChanged("IdKhachHang");
					this.OnIdKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhachHang", DbType="NVarChar(50)")]
		public string TenKhachHang
		{
			get
			{
				return this._TenKhachHang;
			}
			set
			{
				if ((this._TenKhachHang != value))
				{
					this.OnTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._TenKhachHang = value;
					this.SendPropertyChanged("TenKhachHang");
					this.OnTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTKhachHang", DbType="Int")]
		public System.Nullable<int> SDTKhachHang
		{
			get
			{
				return this._SDTKhachHang;
			}
			set
			{
				if ((this._SDTKhachHang != value))
				{
					this.OnSDTKhachHangChanging(value);
					this.SendPropertyChanging();
					this._SDTKhachHang = value;
					this.SendPropertyChanged("SDTKhachHang");
					this.OnSDTKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiGiaoHang", DbType="NVarChar(MAX)")]
		public string DiaChiGiaoHang
		{
			get
			{
				return this._DiaChiGiaoHang;
			}
			set
			{
				if ((this._DiaChiGiaoHang != value))
				{
					this.OnDiaChiGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._DiaChiGiaoHang = value;
					this.SendPropertyChanged("DiaChiGiaoHang");
					this.OnDiaChiGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinKhachHang")]
	public partial class ThongTinKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKhachHang;
		
		private string _EmailKhachHang;
		
		private System.Nullable<int> _SDTKhachHang;
		
		private string _DiaChiKhachHang;
		
		private string _NoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKhachHangChanging(int value);
    partial void OnIdKhachHangChanged();
    partial void OnEmailKhachHangChanging(string value);
    partial void OnEmailKhachHangChanged();
    partial void OnSDTKhachHangChanging(System.Nullable<int> value);
    partial void OnSDTKhachHangChanged();
    partial void OnDiaChiKhachHangChanging(string value);
    partial void OnDiaChiKhachHangChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public ThongTinKhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKhachHang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKhachHang
		{
			get
			{
				return this._IdKhachHang;
			}
			set
			{
				if ((this._IdKhachHang != value))
				{
					this.OnIdKhachHangChanging(value);
					this.SendPropertyChanging();
					this._IdKhachHang = value;
					this.SendPropertyChanged("IdKhachHang");
					this.OnIdKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailKhachHang", DbType="NVarChar(50)")]
		public string EmailKhachHang
		{
			get
			{
				return this._EmailKhachHang;
			}
			set
			{
				if ((this._EmailKhachHang != value))
				{
					this.OnEmailKhachHangChanging(value);
					this.SendPropertyChanging();
					this._EmailKhachHang = value;
					this.SendPropertyChanged("EmailKhachHang");
					this.OnEmailKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTKhachHang", DbType="Int")]
		public System.Nullable<int> SDTKhachHang
		{
			get
			{
				return this._SDTKhachHang;
			}
			set
			{
				if ((this._SDTKhachHang != value))
				{
					this.OnSDTKhachHangChanging(value);
					this.SendPropertyChanging();
					this._SDTKhachHang = value;
					this.SendPropertyChanged("SDTKhachHang");
					this.OnSDTKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKhachHang", DbType="NVarChar(50)")]
		public string DiaChiKhachHang
		{
			get
			{
				return this._DiaChiKhachHang;
			}
			set
			{
				if ((this._DiaChiKhachHang != value))
				{
					this.OnDiaChiKhachHangChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKhachHang = value;
					this.SendPropertyChanged("DiaChiKhachHang");
					this.OnDiaChiKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinTuc")]
	public partial class TinTuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTinTuc;
		
		private string _HinhAnh;
		
		private string _Ten;
		
		private string _IdDanhMucTT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTinTucChanging(int value);
    partial void OnIdTinTucChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnIdDanhMucTTChanging(string value);
    partial void OnIdDanhMucTTChanged();
    #endregion
		
		public TinTuc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTinTuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTinTuc
		{
			get
			{
				return this._IdTinTuc;
			}
			set
			{
				if ((this._IdTinTuc != value))
				{
					this.OnIdTinTucChanging(value);
					this.SendPropertyChanging();
					this._IdTinTuc = value;
					this.SendPropertyChanged("IdTinTuc");
					this.OnIdTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucTT", DbType="NVarChar(50)")]
		public string IdDanhMucTT
		{
			get
			{
				return this._IdDanhMucTT;
			}
			set
			{
				if ((this._IdDanhMucTT != value))
				{
					this.OnIdDanhMucTTChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucTT = value;
					this.SendPropertyChanged("IdDanhMucTT");
					this.OnIdDanhMucTTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMucKhuyenmai")]
	public partial class DanhMucKhuyenmai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDanhMucKhuyenMai;
		
		private string _TenDanhMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDanhMucKhuyenMaiChanging(int value);
    partial void OnIdDanhMucKhuyenMaiChanged();
    partial void OnTenDanhMucChanging(string value);
    partial void OnTenDanhMucChanged();
    #endregion
		
		public DanhMucKhuyenmai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucKhuyenMai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDanhMucKhuyenMai
		{
			get
			{
				return this._IdDanhMucKhuyenMai;
			}
			set
			{
				if ((this._IdDanhMucKhuyenMai != value))
				{
					this.OnIdDanhMucKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucKhuyenMai = value;
					this.SendPropertyChanged("IdDanhMucKhuyenMai");
					this.OnIdDanhMucKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMuc", DbType="NVarChar(50)")]
		public string TenDanhMuc
		{
			get
			{
				return this._TenDanhMuc;
			}
			set
			{
				if ((this._TenDanhMuc != value))
				{
					this.OnTenDanhMucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMuc = value;
					this.SendPropertyChanged("TenDanhMuc");
					this.OnTenDanhMucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhmucSp")]
	public partial class DanhmucSp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDanhMucSanPham;
		
		private string _TenDanhMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDanhMucSanPhamChanging(int value);
    partial void OnIdDanhMucSanPhamChanged();
    partial void OnTenDanhMucChanging(string value);
    partial void OnTenDanhMucChanged();
    #endregion
		
		public DanhmucSp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDanhMucSanPham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDanhMucSanPham
		{
			get
			{
				return this._IdDanhMucSanPham;
			}
			set
			{
				if ((this._IdDanhMucSanPham != value))
				{
					this.OnIdDanhMucSanPhamChanging(value);
					this.SendPropertyChanging();
					this._IdDanhMucSanPham = value;
					this.SendPropertyChanged("IdDanhMucSanPham");
					this.OnIdDanhMucSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMuc", DbType="NVarChar(50)")]
		public string TenDanhMuc
		{
			get
			{
				return this._TenDanhMuc;
			}
			set
			{
				if ((this._TenDanhMuc != value))
				{
					this.OnTenDanhMucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMuc = value;
					this.SendPropertyChanged("TenDanhMuc");
					this.OnTenDanhMucChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
